### ISSUE TITLE
Rails 3 app with signatory won't start

### ISSUE THREAD

**Issue by davidray** [rgarver/signatory#4]
I added signatory to my gemfile, bundled it, and tried to start my server, but get the following error:

NoMethodError: undefined method `read_inheritable_attribute' for Signatory::Document:Class

Here's my gemfile.lock:

GIT
  remote: git://github.com/mileszs/wicked_pdf.git
  revision: 565e4b91ca47f8b97fc70df8895a6839f53bef69
  specs:
    wicked_pdf (0.7.9)
      rails

GIT
  remote: git://github.com/zanker/docusign_rest.git
  revision: 9b5013bbaffa7c9e4130c9f1cd958f734a346fda
  specs:
    docusign_rest (0.0.9)
      json
      multipart-post (>= 1.1.5)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.1)
      actionpack (= 3.2.1)
      mail (~> 2.4.0)
    actionpack (3.2.1)
      activemodel (= 3.2.1)
      activesupport (= 3.2.1)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.1)
      rack (~> 1.4.0)
      rack-cache (~> 1.1)
      rack-test (~> 0.6.1)
      sprockets (~> 2.1.2)
    activeadmin (0.4.4)
      bourbon (>= 1.0.0)
      devise (>= 1.1.2)
      fastercsv
      formtastic (~> 2.1.1)
      inherited_resources (>= 1.3.1)
      jquery-rails (>= 1.0.0)
      kaminari (>= 0.13.0)
      meta_search (>= 0.9.2)
      rails (>= 3.0.0)
      sass (>= 3.1.0)
    activemodel (3.2.1)
      activesupport (= 3.2.1)
      builder (~> 3.0.0)
    activerecord (3.2.1)
      activemodel (= 3.2.1)
      activesupport (= 3.2.1)
      arel (~> 3.0.0)
      tzinfo (~> 0.3.29)
    activeresource (3.2.1)
      activemodel (= 3.2.1)
      activesupport (= 3.2.1)
    activesupport (3.2.1)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    addressable (2.3.2)
    andand (1.3.3)
    arel (3.0.2)
    audited (3.0.0.rc2)
    audited-activerecord (3.0.0.rc2)
      activerecord (~> 3.0)
      audited (= 3.0.0.rc2)
    aws-s3 (0.6.3)
      builder
      mime-types
      xml-simple
    aws-sdk (1.6.4)
      httparty (~> 0.7)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
      uuidtools (~> 2.1)
    aws-ses (0.4.4)
      builder
      mail (> 2.2.5)
      mime-types
      xml-simple
    aws_cf_signer (0.1.1)
    bcrypt-ruby (3.0.1)
    bourbon (2.1.1)
      sass (>= 3.1)
    builder (3.0.0)
    capistrano (2.13.3)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capistrano-ext (1.2.1)
      capistrano (>= 1.0.0)
    capistrano-helpers (0.7.1)
      capistrano
      git
      tinder
    capistrano_colors (0.5.5)
    chronic (0.6.7)
    ckeditor (3.7.0.rc3)
      mime-types (~> 1.17.2)
      orm_adapter (~> 0.0.6)
    cocaine (0.2.1)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.3.3)
    country-select (1.1.1)
    daemon_controller (1.0.0)
    devise (2.1.0)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.0.7)
      railties (~> 3.1)
      warden (~> 1.1.1)
    devise_invitable (1.0.3)
      actionmailer (~> 3.0)
      devise (>= 2.0.0)
      railties (~> 3.0)
    diff-lcs (1.1.3)
    dropbox-sdk (1.3)
      json
    erubis (2.7.0)
    eventmachine (0.12.10)
    exceptional (2.0.32)
      rack
    execjs (1.4.0)
      multi_json (~> 1.0)
    factory_girl (4.0.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.0.0)
      factory_girl (~> 4.0.0)
      railties (>= 3.0.0)
    faraday (0.8.4)
      multipart-post (~> 1.1)
    faraday_middleware (0.8.8)
      faraday (>= 0.7.4, < 0.9)
    fastercsv (1.5.5)
    fastthread (1.0.7)
    ffi (1.1.5)
    formtastic (2.1.1)
      actionpack (~> 3.0)
    git (1.2.5)
    growl (1.0.3)
    guard (1.3.2)
      listen (>= 0.4.2)
      thor (>= 0.14.6)
    guard-rspec (1.2.1)
      guard (>= 1.1)
    guard-spork (1.1.0)
      guard (>= 1.1)
      spork (>= 0.8.4)
    haml (3.1.7)
    has_scope (0.5.1)
    hashie (1.2.0)
    highline (1.6.14)
    hike (1.2.1)
    http_parser.rb (0.5.3)
    httparty (0.8.3)
      multi_json (~> 1.0)
      multi_xml
    httpauth (0.1)
    i18n (0.6.0)
    inherited_resources (1.3.1)
      has_scope (~> 0.5.0)
      responders (~> 0.6)
    journey (1.0.4)
    jquery-rails (2.0.3)
      railties (>= 3.1.0, < 5.0)
      thor (~> 0.14)
    json (1.7.5)
    jwt (0.1.5)
      multi_json (>= 1.0)
    kaminari (0.13.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
      railties (>= 3.0.0)
    launchy (2.1.2)
      addressable (~> 2.3)
    letter_opener (0.0.2)
      launchy
    libv8 (3.3.10.4)
    listen (0.4.7)
      rb-fchange (~> 0.0.5)
      rb-fsevent (~> 0.9.1)
      rb-inotify (~> 0.8.8)
    mail (2.4.4)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    meta_search (1.1.3)
      actionpack (~> 3.1)
      activerecord (~> 3.1)
      activesupport (~> 3.1)
      polyamorous (~> 0.5.0)
    mime-types (1.17.2)
    multi_json (1.3.6)
    multi_xml (0.5.1)
    multipart-post (1.1.5)
    mysql2 (0.3.11)
    nested_form (0.2.3)
    net-scp (1.0.4)
      net-ssh (>= 1.99.1)
    net-sftp (2.0.5)
      net-ssh (>= 2.0.9)
    net-ssh (2.5.2)
    net-ssh-gateway (1.1.0)
      net-ssh (>= 1.99.1)
    newrelic_rpm (3.4.1)
    nokogiri (1.5.5)
    oauth (0.4.3)
    oauth2 (0.8.0)
      faraday (~> 0.8)
      httpauth (~> 0.1)
      jwt (~> 0.1.4)
      multi_json (~> 1.0)
      rack (~> 1.2)
    omniauth (1.1.0)
      hashie (~> 1.2)
      rack
    omniauth-facebook (1.3.0)
      omniauth-oauth2 (~> 1.0.2)
    omniauth-linkedin (0.0.8)
      omniauth-oauth (~> 1.0)
    omniauth-oauth (1.0.1)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.0.3)
      oauth2 (~> 0.8.0)
      omniauth (~> 1.0)
    omniauth-openid (1.0.1)
      omniauth (~> 1.0)
      rack-openid (~> 1.3.1)
    orm_adapter (0.0.7)
    paperclip (2.7.0)
      activerecord (>= 2.3.0)
      activesupport (>= 2.3.2)
      cocaine (>= 0.0.2)
      mime-types
    passenger (3.0.17)
      daemon_controller (>= 1.0.0)
      fastthread (>= 1.0.1)
      rack
      rake (>= 0.8.1)
    polyamorous (0.5.0)
      activerecord (~> 3.0)
    polyglot (0.3.3)
    rack (1.4.1)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-openid (1.3.1)
      rack (>= 1.1.0)
      ruby-openid (>= 2.1.8)
    rack-ssl (1.3.2)
      rack
    rack-test (0.6.1)
      rack (>= 1.0)
    rails (3.2.1)
      actionmailer (= 3.2.1)
      actionpack (= 3.2.1)
      activerecord (= 3.2.1)
      activeresource (= 3.2.1)
      activesupport (= 3.2.1)
      bundler (~> 1.0)
      railties (= 3.2.1)
    rails3-generators (0.17.4)
      railties (>= 3.0.0)
    railties (3.2.1)
      actionpack (= 3.2.1)
      activesupport (= 3.2.1)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (~> 0.14.6)
    rake (0.9.2.2)
    rb-fchange (0.0.5)
      ffi
    rb-fsevent (0.9.1)
    rb-inotify (0.8.8)
      ffi (>= 0.5.0)
    rdoc (3.12)
      json (~> 1.4)
    responders (0.9.2)
      railties (~> 3.1)
    rspec (2.11.0)
      rspec-core (~> 2.11.0)
      rspec-expectations (~> 2.11.0)
      rspec-mocks (~> 2.11.0)
    rspec-core (2.11.1)
    rspec-expectations (2.11.2)
      diff-lcs (~> 1.1.3)
    rspec-mocks (2.11.2)
    rspec-rails (2.11.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec (~> 2.11.0)
    ruby-openid (2.2.0)
    sass (3.2.1)
    sass-rails (3.2.5)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    shoulda (3.1.1)
      shoulda-context (~> 1.0)
      shoulda-matchers (~> 1.2)
    shoulda-context (1.0.0)
    shoulda-matchers (1.2.0)
      activesupport (>= 3.0.0)
    signatory (0.0.7)
      activeresource (>= 2.3.9)
      bundler (>= 1.0.0)
      oauth (= 0.4.3)
    simple_oauth (0.1.9)
    simplecov (0.6.4)
      multi_json (~> 1.0)
      simplecov-html (~> 0.5.3)
    simplecov-html (0.5.3)
    simplecov-rcov (0.2.3)
      simplecov (>= 0.4.1)
    spork (0.9.2)
    sprockets (2.1.3)
      hike (~> 1.2)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.6)
    therubyracer (0.10.2)
      libv8 (~> 3.3.10)
    thor (0.14.6)
    tilt (1.3.3)
    timeliness (0.3.6)
    tinder (1.9.0)
      activesupport (>= 2.3, < 4)
      eventmachine (>= 0.12.0, < 2)
      faraday (~> 0.8)
      faraday_middleware (~> 0.8)
      hashie (~> 1.0)
      json (~> 1.6)
      mime-types (~> 1.16)
      multi_json (~> 1.0)
      multipart-post (~> 1.1)
      twitter-stream (~> 0.1)
    treetop (1.4.10)
      polyglot
      polyglot (>= 0.3.1)
    twitter-stream (0.1.16)
      eventmachine (>= 0.12.8)
      http_parser.rb (~> 0.5.1)
      simple_oauth (~> 0.1.4)
    tzinfo (0.3.33)
    uglifier (1.2.7)
      execjs (>= 0.3.0)
      multi_json (~> 1.3)
    uuidtools (2.1.3)
    validates_timeliness (3.0.14)
      timeliness (~> 0.3.6)
    warden (1.1.1)
      rack (>= 1.0)
    webrat (0.7.3)
      nokogiri (>= 1.2.0)
      rack (>= 1.0)
      rack-test (>= 0.5.3)
    webshims-rails (0.2)
      rails (> 3.1.0)
    whenever (0.7.3)
      activesupport (>= 2.3.4)
      chronic (~> 0.6.3)
    xml-simple (1.1.1)
    yard (0.8.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  activeadmin
  andand
  audited-activerecord (~> 3.0.0.rc2)
  aws-s3
  aws-sdk
  aws-ses (~> 0.4.4)
  aws_cf_signer
  capistrano
  capistrano-ext
  capistrano-helpers
  capistrano_colors
  ckeditor (= 3.7.0.rc3)
  coffee-rails (~> 3.2.1)
  country-select (~> 1.1.1)
  devise
  devise_invitable (~> 1.0.0)
  docusign_rest!
  dropbox-sdk
  exceptional
  execjs
  factory_girl_rails
  growl
  guard
  guard-rspec
  guard-spork
  haml
  jquery-rails (~> 2.0.2)
  letter_opener
  meta_search (>= 1.1.0.pre)
  mysql2
  nested_form
  newrelic_rpm
  omniauth (= 1.1.0)
  omniauth-facebook (~> 1.3.0)
  omniauth-linkedin (~> 0.0.6)
  omniauth-openid (~> 1.0.1)
  paperclip (~> 2.7)
  passenger
  rails (= 3.2.1)
  rails3-generators
  rb-fchange
  rb-fsevent
  rb-inotify
  rspec
  rspec-rails
  sass-rails (~> 3.2.3)
  shoulda
  signatory (~> 0.0.7)
  simplecov
  simplecov-rcov
  sqlite3
  therubyracer
  uglifier (>= 1.0.3)
  validates_timeliness (~> 3.0.2)
  webrat
  webshims-rails
  whenever
  wicked_pdf!
  yard

**Comment by rgarver** [comment]
Good find @davidray. This was apparently removed in rails 3.2. See: http://apidock.com/rails/v3.1.0/Class/read_inheritable_attribute

The new replacement is apparently: http://apidock.com/rails/v3.2.1/Class/class_attribute

Ideally the fix would work for both versions of rails/activesupport, obviously. It would be even better if we could get rid of the rails dependency or at least make the activesupport dependency explicit.

I'm not sure I'll have a chance to dive in to this fully until next week, but if you want to submit a pull request I'll try and review it and merge it in for an updated release ASAP.

**Comment by rgarver** [comment]
As of commit 38f32eca7 you should be good to go on this. I'll package up a new release. This is now wired to travis-ci as well and tested against ActiveSupport 3.0 and 3.2 for ruby versions 1.8.7, 1.9.2, and 1.9.3.

**Comment by davidray** [comment]
Thanks! We went with DocuSign for the time being but I may be able to
circle back and try this again in a few months.

Best,

David Christiansen
@aldos http://twitter.com/aldos
TechDarkSide.com http://techdarkside.com
317-966-6154 (mobile)

http://bookstore.booktango.com/Products/SKU-000549028/Genesis-20.aspx
http://bookstore.booktango.com/Products/SKU-000550903/Alter-Ego.aspx
